-- migrate:up
WITH category_pairs(parent_name, child_name) AS (
  VALUES
    ('Home', 'Mortgage'),
    ('Home', 'Rent'),
    ('Home', 'Home Insurance'),
    ('Home', 'Rental Insurance'),
    ('Home', 'HOA Dues'),
    ('Home', 'Home Supplies'),
    ('Home', 'Home Maintenance'),
    ('Home', 'Flood Insurance'),
    ('Home', 'Furniture'),
    ('Home', 'Furnishings'),
    ('Auto', 'Car Payment'),
    ('Auto', 'Car Insurance'),
    ('Auto', 'Car Maintenance'),
    ('Auto', 'Gas & Fuel'),
    ('Auto', 'Car Wash'),
    ('Auto', 'Toll'),
    ('Auto', 'Inspection & Registration'),
    ('Auto', 'Public Transportation'),
    ('Auto', 'Rideshare'),
    ('Auto', 'Parking'),
    ('Food', 'Groceries'),
    ('Food', 'Restaurants'),
    ('Food', 'Fast Food'),
    ('Food', 'Coffee Shop'),
    ('Education', 'Tuition'),
    ('Education', 'Student Loan'),
    ('Education', 'Books & Supplies'),
    ('Entertainment', 'Movies'),
    ('Entertainment', 'Family Night'),
    ('Entertainment', 'Date Night'),
    ('Financial', 'Life Insurance'),
    ('Financial', 'Retirement Savings'),
    ('Financial', 'Investments'),
    ('Fitness', 'Gym Membership'),
    ('Fitness', 'Personal Training'),
    ('Health', 'Suppliments'),
    ('Health', 'Doctor'),
    ('Health', 'Dentist'),
    ('Health', 'Health Insurance'),
    ('Health', 'Health Share'),
    ('Health', 'Eyecare'),
    ('Health', 'Pharmacy'),
    ('Kids', 'Child Care'),
    ('Kids', 'Child Clothing'),
    ('Kids', 'Babysitter'),
    ('Kids', 'Diapers'),
    ('Kids', 'Formula'),
    ('Kids', 'Toys'),
    ('Personal Care', 'Salon'),
    ('Personal Care', 'Barber'),
    ('Personal Care', 'Spa'),
    ('Personal Care', 'Laundry'),
    ('Savings', 'Emergency Fund'),
    ('Savings', 'Vacation Fund'),
    ('Savings', 'Car Fund'),
    ('Pets', 'Veterinary'),
    ('Pets', 'Pet Food'),
    ('Pets', 'Pet Grooming'),
    ('Pets', 'Pet Boarding'),
    ('Shopping', 'Electronics'),
    ('Shopping', 'Clothing'),
    ('Shopping', 'Books'),
    ('Travel', 'Airfare'),
    ('Travel', 'Rental Cars'),
    ('Travel', 'Hotels'),
    ('Utilities', 'Electricity'),
    ('Utilities', 'Water'),
    ('Utilities', 'Gas'),
    ('Utilities', 'Internet & Cable'),
    ('Utilities', 'Phone'),
    ('Utilities', 'Trash'),
    ('Income', 'Paycheck'),
    ('Income', 'Bonus'),
    ('Income', 'Tax Refund'),
    ('Income', 'Earned Interest'),
    ('Income', 'Dividends'),
    ('Income', 'Rental Income')
)
UPDATE categories child
SET parent_id = parent.id,
    updated_at = NOW()
FROM categories parent, category_pairs
WHERE child.user_id = parent.user_id
  AND child.type = parent.type
  AND LOWER(child.name) = LOWER(category_pairs.child_name)
  AND LOWER(parent.name) = LOWER(category_pairs.parent_name)
  AND child.parent_id IS NULL;

-- migrate:down
WITH category_pairs(parent_name, child_name) AS (
  VALUES
    ('Home', 'Mortgage'),
    ('Home', 'Rent'),
    ('Home', 'Home Insurance'),
    ('Home', 'Rental Insurance'),
    ('Home', 'HOA Dues'),
    ('Home', 'Home Supplies'),
    ('Home', 'Home Maintenance'),
    ('Home', 'Flood Insurance'),
    ('Home', 'Furniture'),
    ('Home', 'Furnishings'),
    ('Auto', 'Car Payment'),
    ('Auto', 'Car Insurance'),
    ('Auto', 'Car Maintenance'),
    ('Auto', 'Gas & Fuel'),
    ('Auto', 'Car Wash'),
    ('Auto', 'Toll'),
    ('Auto', 'Inspection & Registration'),
    ('Auto', 'Public Transportation'),
    ('Auto', 'Rideshare'),
    ('Auto', 'Parking'),
    ('Food', 'Groceries'),
    ('Food', 'Restaurants'),
    ('Food', 'Fast Food'),
    ('Food', 'Coffee Shop'),
    ('Education', 'Tuition'),
    ('Education', 'Student Loan'),
    ('Education', 'Books & Supplies'),
    ('Entertainment', 'Movies'),
    ('Entertainment', 'Family Night'),
    ('Entertainment', 'Date Night'),
    ('Financial', 'Life Insurance'),
    ('Financial', 'Retirement Savings'),
    ('Financial', 'Investments'),
    ('Fitness', 'Gym Membership'),
    ('Fitness', 'Personal Training'),
    ('Health', 'Suppliments'),
    ('Health', 'Doctor'),
    ('Health', 'Dentist'),
    ('Health', 'Health Insurance'),
    ('Health', 'Health Share'),
    ('Health', 'Eyecare'),
    ('Health', 'Pharmacy'),
    ('Kids', 'Child Care'),
    ('Kids', 'Child Clothing'),
    ('Kids', 'Babysitter'),
    ('Kids', 'Diapers'),
    ('Kids', 'Formula'),
    ('Kids', 'Toys'),
    ('Personal Care', 'Salon'),
    ('Personal Care', 'Barber'),
    ('Personal Care', 'Spa'),
    ('Personal Care', 'Laundry'),
    ('Savings', 'Emergency Fund'),
    ('Savings', 'Vacation Fund'),
    ('Savings', 'Car Fund'),
    ('Pets', 'Veterinary'),
    ('Pets', 'Pet Food'),
    ('Pets', 'Pet Grooming'),
    ('Pets', 'Pet Boarding'),
    ('Shopping', 'Electronics'),
    ('Shopping', 'Clothing'),
    ('Shopping', 'Books'),
    ('Travel', 'Airfare'),
    ('Travel', 'Rental Cars'),
    ('Travel', 'Hotels'),
    ('Utilities', 'Electricity'),
    ('Utilities', 'Water'),
    ('Utilities', 'Gas'),
    ('Utilities', 'Internet & Cable'),
    ('Utilities', 'Phone'),
    ('Utilities', 'Trash'),
    ('Income', 'Paycheck'),
    ('Income', 'Bonus'),
    ('Income', 'Tax Refund'),
    ('Income', 'Earned Interest'),
    ('Income', 'Dividends'),
    ('Income', 'Rental Income')
)
UPDATE categories child
SET parent_id = NULL,
    updated_at = NOW()
FROM categories parent, category_pairs
WHERE child.parent_id = parent.id
  AND child.user_id = parent.user_id
  AND child.type = parent.type
  AND LOWER(child.name) = LOWER(category_pairs.child_name)
  AND LOWER(parent.name) = LOWER(category_pairs.parent_name);
